"""
Django settings for treasure project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from enum import Enum


# Where is the app being deployed?
class Deployment(Enum):
    LOCAL = 1
    HEROKU = 2
    AZURE = 3


DEPLOYMENT = Deployment[os.getenv("DEPLOYMENT", "LOCAL")]
LOCAL = DEPLOYMENT == Deployment.LOCAL

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = LOCAL

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "insecure" if LOCAL else "")

ALLOWED_HOSTS = ["localhost"] if LOCAL else [os.environ.get("APP_URL", "")]

# Extra settings from security check
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = DEPLOYMENT == Deployment.HEROKU
SESSION_COOKIE_SECURE = not LOCAL
CSRF_COOKIE_SECURE = not LOCAL
X_FRAME_OPTIONS = "DENY"

# Close the session when user closes the browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
CSRF_COOKIE_AGE = 5184000

# Storage.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
if DEPLOYMENT == Deployment.LOCAL:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
elif DEPLOYMENT == Deployment.AZURE:
    DEFAULT_FILE_STORAGE = "hunt.backend.AzureMediaStorage"
    STATICFILES_STORAGE = "hunt.backend.AzureStaticStorage"
    AZURE_ACCOUNT_NAME = os.getenv("AZURE_ACCOUNT_NAME", "etreasurehuntstorage")
    AZURE_ACCOUNT_KEY = os.getenv("AZURE_ACCOUNT_KEY")
    AZURE_MEDIA_CONTAINER = os.getenv("AZURE_MEDIA_CONTAINER", "media")
    AZURE_STATIC_CONTAINER = os.getenv("AZURE_STATIC_CONTAINER", "static")
elif DEPLOYMENT == Deployment.HEROKU:
    DEFAULT_FILE_STORAGE = "storages.backends.dropbox.DropBoxStorage"
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    DROPBOX_OAUTH2_TOKEN = os.environ.get("DROPBOX_OAUTH2_TOKEN", "")
    DROPBOX_ROOT_PATH = "/"

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "storages",
    "hunt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "treasure.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "treasure.wsgi.application"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "ERROR"),
        }
    },
}

if DEPLOYMENT == Deployment.HEROKU:
    import django_heroku

    django_heroku.settings(locals(), logging=False)

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAdminUser"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

if DEPLOYMENT == Deployment.LOCAL:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": "treasure.sqlite",
        }
    }
elif DEPLOYMENT == Deployment.AZURE:
    user = os.getenv("DBUSER", "")
    host = os.getenv("DBHOST", "")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DBNAME", "treasurehuntdb"),
            "USER": f"{user}@{host}",
            "PASSWORD": os.getenv("DBPASS", ""),
            "HOST": host,
        }
    }
elif DEPLOYMENT == Deployment.HEROKU:
    # Heroku takes care of this automatically.
    pass
