# Generated by Django 3.2 on 2021-04-07 10:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('active', models.BooleanField(default=True, primary_key=True, serialize=False)),
                ('use_alternative_map', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HuntInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('level', models.IntegerField(default=1)),
                ('hints_shown', models.IntegerField(default=1)),
                ('hint_requested', models.BooleanField(default=False)),
                ('next_hint_release', models.DateTimeField(blank=True, null=True)),
                ('slack_channel', models.CharField(blank=True, default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=5000)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('tolerance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HuntEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('type', models.CharField(choices=[('REQ', 'Hint requested'), ('REL', 'Hints released'), ('ADV', 'Advanced level')], max_length=3)),
                ('level', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='hints')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='hunt.level')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hint',
            constraint=models.UniqueConstraint(fields=('level', 'number'), name='unique hint'),
        ),
    ]
