# Generated by Django 3.2.6 on 2021-08-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntinfo',
            name='slack_channel',
        ),
    ]
