# Generated by Django 3.0.4 on 2020-03-29 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='clues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), default=list, size=None),
        ),
    ]
