# Generated by Django 3.1.6 on 2021-02-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['level', 'number']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='hint',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='hunt.level'),
        ),
        migrations.AddConstraint(
            model_name='hint',
            constraint=models.UniqueConstraint(fields=('level', 'number'), name='unique hint'),
        ),
    ]
