# Generated by Django 3.1.6 on 2021-02-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_auto_20210208_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
    ]
