# Generated by Django 4.0.5 on 2022-06-13 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0002_remove_huntinfo_slack_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=7, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='level',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
