# Generated by Django 4.2.3 on 2023-07-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hunt", "0003_alter_level_latitude_alter_level_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("room", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("date_added",),
            },
        ),
    ]
