# Generated by Django 2.2.3 on 2020-03-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_huntinfo_hint_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='next_hint_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
