# Generated by Django 3.1.6 on 2021-02-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_auto_20210209_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='image',
            field=models.ImageField(upload_to='hints'),
        ),
    ]
