# Generated by Django 3.0.4 on 2020-03-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_userlevel_next_hint_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntinfo',
            name='hints_shown',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huntinfo',
            name='next_hint_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huntinfo',
            name='slack_channel',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.DeleteModel(
            name='UserLevel',
        ),
    ]
