# Generated by Django 3.0.4 on 2020-03-29 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hunt", "0005_auto_20200315_2108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huntinfo",
            name="user",
            field=models.OneToOneField(
                default="admin",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        )
    ]
